name: Cloudflare Pages Deployment

on:
  push:
    branches:
      - main

jobs:
  cf:
    name: Build & Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # - name: Publish #1
      #   uses: cloudflare/pages-action@1
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      #     projectName: zerodayalliance
      #     directory: public

      - name: Publish #2
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: zerodayalliancesnu
          directory: public

      - name: Publish #3
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: zeroday-alliance-snu
          directory: public

      # - name: Publish #4
      #   uses: cloudflare/pages-action@1
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      #     projectName: zeroday-alliance
      #     directory: public